import { css } from '@styled-system/css';

export const styles = {
  header: css({
    position: 'fixed',
    top: 0,
    width: '100%',
    height: '100px',
    backgroundColor: 'white',
    zIndex: 50,
    borderBottom: '1px solid #f3f4f6',
  }),
  nav: css({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: '100%',
    paddingLeft: '50px',
    paddingRight: '50px',
  }),
  logoImage: css({ 
    width: '83px', 
    height: '81px', 
    objectFit: 'contain', 
    display: 'block' 
  }),
  menuList: css({
    display: 'flex',
    alignItems: 'stretch',
    height: '100px',
    listStyle: 'none',
    margin: 0,
    padding: 0,
  }),
  menuItem: css({ position: 'relative' }),
  menuLink: (isActive: boolean, isOpen: boolean) => css({
    display: 'flex',
    alignItems: 'center',
    height: '100px',
    paddingLeft: '26px',
    paddingRight: '26px',
    fontSize: '15px',
    fontWeight: '800',
    textDecoration: 'none',
    whiteSpace: 'nowrap',
    color: isActive || isOpen ? '#267db6' : '#1f1e1e',
    transition: 'color 0.2s, border-color 0.2s',
  }),
  subMenuList: css({
    position: 'absolute',
    top: '100px',
    left: 0,
    minWidth: 'max-content',
    listStyle: 'none',
    margin: 0,
    backgroundColor: 'white',
    borderLeft: '1px solid #e5e7eb',
    borderRight: '1px solid #e5e7eb',
    borderBottom: '1px solid #e5e7eb',
    boxShadow: '0 4px 16px rgba(0,0,0,0.10)',
    zIndex: 100,
  }),
  subMenuLink: (isActive: boolean) => css({
    display: 'block',
    paddingTop: '12px',
    paddingBottom: '12px',
    paddingLeft: '26px',
    paddingRight: '26px',
    fontSize: '15px',
    fontWeight: isActive ? '700' : '400',
    color: isActive ? 'white' : '#333',
    backgroundColor: isActive ? '#267db6' : 'transparent',
    textDecoration: 'none',
    whiteSpace: 'nowrap',
    _hover: {
      backgroundColor: isActive ? '#1d6a9f' : '#f0f7ff',
      color: isActive ? 'white' : '#267db6',
    },
  }),
  inquiryButton: css({
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    paddingTop: '10px',
    paddingBottom: '10px',
    paddingLeft: '20px',
    paddingRight: '20px',
    backgroundColor: '#267db6',
    color: 'white',
    fontSize: '15px',
    fontWeight: '700',
    textDecoration: 'none',
    borderRadius: '9999px',
    whiteSpace: 'nowrap',
    flexShrink: 0,
    transition: 'background-color 0.2s',
    _hover: { backgroundColor: '#1d6a9f' },
  })
};
