import { css } from '@styled-system/css';

export const styles = {
  section: css({
    position: 'relative',
    width: '100%',
    height: '100vh',
    overflow: 'hidden',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  }),
  overlay: css({ 
    position: 'absolute', 
    inset: 0, 
    backgroundColor: 'rgba(0,0,0,0.45)', 
    zIndex: 1 
  }),
  contentContainer: css({
    position: 'relative',
    zIndex: 10,
    textAlign: 'center',
    paddingLeft: '24px',
    paddingRight: '24px',
    maxWidth: '800px',
  }),
  title: css({
    fontSize: { base: '36px', md: '64px' },
    fontWeight: '800',
    color: 'white',
    lineHeight: '1.3',
    marginBottom: '20px',
    wordBreak: 'keep-all',
    overflowWrap: 'break-word',
    opacity: 0,
    animation: 'fadeSlideUp 0.7s ease forwards',
    animationDelay: '0.1s',
  }),
  subtitle: css({
    color: 'rgba(255,255,255,0.85)',
    fontSize: { base: '16px', md: '20px' },
    lineHeight: '1.7',
    marginBottom: '36px',
    wordBreak: 'keep-all',
    overflowWrap: 'break-word',
    opacity: 0,
    animation: 'fadeSlideUp 0.7s ease forwards',
    animationDelay: '0.5s',
  }),
  button: css({
    display: 'inline-flex',
    alignItems: 'center',
    paddingTop: '18px',
    paddingBottom: '18px',
    paddingLeft: '44px',
    paddingRight: '44px',
    backgroundColor: '#267db6',
    color: 'white',
    fontSize: '20px',
    fontWeight: '700',
    textDecoration: 'none',
    borderRadius: '9999px',
    transition: 'background-color 0.2s, transform 0.2s',
    opacity: 0,
    animation: 'fadeSlideUp 0.7s ease forwards',
    animationDelay: '0.9s',
    _hover: {
      backgroundColor: '#1d6a9f',
      transform: 'translateY(-2px)',
    },
  }),
  indicatorContainer: css({
    position: 'absolute',
    bottom: '50px',
    left: '50%',
    zIndex: 10,
    display: 'flex',
    gap: '12px',
  }),
  indicatorButton: (isActive: boolean) => css({
    width: isActive ? '40px' : '14px',
    height: '14px',
    borderRadius: '9999px',
    border: 'none',
    cursor: 'pointer',
    transition: 'all 0.3s',
    backgroundColor: isActive ? 'white' : 'rgba(255,255,255,0.45)',
  })
};
