import { css } from '@styled-system/css';

export const styles = {
  headerSection: css({
    paddingTop: { base: '60px', md: '80px' },
    paddingBottom: { base: '40px', md: '60px' },
    paddingLeft: { base: '20px', md: '50px' },
    paddingRight: { base: '20px', md: '50px' },
    backgroundColor: 'white',
    textAlign: 'center',
  }),
  headerBadge: css({
    fontSize: { base: '12px', md: '14px' },
    fontWeight: '600',
    letterSpacing: '2px',
    color: '#0891b2',
    marginBottom: '16px',
    textTransform: 'uppercase',
  }),
  headerTitle: css({
    fontSize: { base: '32px', md: '48px' },
    fontWeight: '700',
    color: '#001428',
    marginBottom: { base: '20px', md: '32px' },
    lineHeight: '1.3',
    wordBreak: 'keep-all',
  }),
  headerDescription: css({
    fontSize: { base: '14px', md: '16px' },
    color: '#4b5563',
    lineHeight: '1.8',
    maxWidth: '700px',
    margin: '0 auto',
    wordBreak: 'keep-all',
  }),
  
  mainSection: css({
    paddingTop: { base: '40px', md: '60px' },
    paddingBottom: { base: '60px', md: '100px' },
    paddingLeft: { base: '20px', md: '50px' },
    paddingRight: { base: '20px', md: '50px' },
    backgroundColor: '#f8fafb',
  }),
  mainGrid: css({
    display: { base: 'block', lg: 'grid' },
    gridTemplateColumns: '1fr 1fr',
    gap: { base: '40px', md: '60px' },
    alignItems: 'start',
    maxWidth: '1400px',
    margin: '0 auto',
  }),
  mainTextContainer: css({
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
  }),
  mainBadge: css({
    fontSize: { base: '12px', md: '13px' },
    fontWeight: '600',
    letterSpacing: '1.5px',
    color: '#0891b2',
    marginBottom: '16px',
    textTransform: 'uppercase',
  }),
  mainTitle: css({
    fontSize: { base: '28px', md: '36px' },
    fontWeight: '700',
    color: '#001428',
    marginBottom: '24px',
    lineHeight: '1.4',
    wordBreak: 'keep-all',
  }),
  mainDescription: css({
    fontSize: { base: '14px', md: '15px' },
    color: '#4b5563',
    lineHeight: '1.8',
    marginBottom: '20px',
    wordBreak: 'keep-all',
  }),
  statsContainer: css({
    display: 'flex',
    gap: '20px',
    marginTop: '24px',
    flexWrap: 'wrap',
    wordBreak: 'keep-all',
  }),
  statValue: css({
    fontSize: '24px',
    fontWeight: '700',
    color: '#0891b2',
  }),
  statLabel: css({
    fontSize: '12px',
    color: '#4b5563',
    marginTop: '4px',
  }),
  imageContainer: css({
    position: 'relative',
    height: { base: '300px', md: '450px' },
    borderRadius: '12px',
    overflow: 'hidden',
    boxShadow: '0 10px 40px rgba(0,0,0,0.1)',
  }),
  imageCover: css({
    objectFit: 'cover',
  }),

  instructorSection: css({
    paddingTop: { base: '60px', md: '80px' },
    paddingBottom: { base: '80px', md: '120px' },
    paddingLeft: { base: '20px', md: '50px' },
    paddingRight: { base: '20px', md: '50px' },
    backgroundColor: 'white',
  }),
  instructorContainer: css({
    maxWidth: '1200px',
    margin: '0 auto',
  }),
  instructorTitle: css({
    fontSize: { base: '28px', md: '36px' },
    fontWeight: '700',
    color: '#001428',
    marginBottom: { base: '40px', md: '60px' },
    textAlign: 'center',
    wordBreak: 'keep-all',
  }),
  instructorGrid: css({
    display: 'grid',
    gridTemplateColumns: { base: '1fr', md: 'repeat(3, 1fr)' },
    gap: { base: '30px', md: '40px' },
  }),
  instructorCard: css({
    cursor: 'pointer',
    transition: 'all 0.3s ease',
  }),
  instructorImageWrapper: css({
    position: 'relative',
    width: '100%',
    height: { base: '320px', md: '380px' },
    borderRadius: '12px',
    overflow: 'hidden',
    marginBottom: '20px',
    transition: 'all 0.3s ease',
    backgroundColor: '#e0f2fe',
  }),
  instructorImage: css({
    objectFit: 'cover',
    transition: 'transform 0.3s ease',
  }),
  instructorOverlay: css({
    position: 'absolute',
    inset: 0,
    background: 'linear-gradient(180deg, rgba(0,0,0,0) 0%, rgba(0,20,40,0.8) 100%)',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-end',
    padding: { base: '24px', md: '28px' },
    transition: 'all 0.3s ease',
  }),
  instructorName: css({
    fontSize: { base: '20px', md: '24px' },
    fontWeight: '700',
    color: 'white',
    marginBottom: '6px',
  }),
  instructorRole: css({
    fontSize: { base: '13px', md: '14px' },
    color: '#0891b2',
    fontWeight: '600',
    marginBottom: '12px',
  }),
  instructorTextInfo: css({
    padding: '0 8px',
  }),
  instructorDesc: css({
    fontSize: { base: '14px', md: '15px' },
    color: '#4b5563',
    lineHeight: '1.6',
    wordBreak: 'keep-all',
    minHeight: { base: '48px', md: '60px' },
    display: 'flex',
    alignItems: 'center',
  }),

  ctaSection: css({
    paddingTop: { base: '60px', md: '80px' },
    paddingBottom: { base: '60px', md: '80px' },
    paddingLeft: { base: '20px', md: '50px' },
    paddingRight: { base: '20px', md: '50px' },
    background: 'linear-gradient(135deg, #0891b2 0%, #0e7490 100%)',
    textAlign: 'center',
  }),
  ctaContainer: css({
    maxWidth: '600px',
    margin: '0 auto',
  }),
  ctaTitle: css({
    fontSize: { base: '28px', md: '36px' },
    fontWeight: '700',
    color: 'white',
    marginBottom: '20px',
    wordBreak: 'keep-all',
  }),
  ctaDescription: css({
    fontSize: { base: '14px', md: '16px' },
    color: 'rgba(255,255,255,0.9)',
    marginBottom: '32px',
    lineHeight: '1.7',
    wordBreak: 'keep-all',
  }),
  ctaButton: css({
    display: 'inline-flex',
    alignItems: 'center',
    paddingTop: '16px',
    paddingBottom: '16px',
    paddingLeft: '40px',
    paddingRight: '40px',
    backgroundColor: 'white',
    color: '#0891b2',
    fontSize: '16px',
    fontWeight: '700',
    textDecoration: 'none',
    borderRadius: '9999px',
    transition: 'all 0.3s ease',
    _hover: {
      backgroundColor: '#f0f9ff',
      transform: 'translateY(-2px)',
    },
  }),
};
